/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lab5_UberSocial;

import javax.swing.JOptionPane;

/**
 *
 * @author jenniferbueso
 */
public class AgregarAmigo extends javax.swing.JFrame {

    /**
     * Creates new form AgregarAmigo
     */
    public AgregarAmigo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonAgregar = new javax.swing.JLabel();
        Usuario2Field = new javax.swing.JTextField();
        Usuario1Field = new javax.swing.JTextField();
        BotonRegresar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 190, 40));

        Usuario2Field.setBackground(new java.awt.Color(202, 240, 248));
        Usuario2Field.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        Usuario2Field.setForeground(new java.awt.Color(0, 0, 0));
        Usuario2Field.setBorder(null);
        jPanel1.add(Usuario2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 368, 240, 40));

        Usuario1Field.setBackground(new java.awt.Color(202, 240, 248));
        Usuario1Field.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        Usuario1Field.setForeground(new java.awt.Color(0, 0, 0));
        Usuario1Field.setBorder(null);
        jPanel1.add(Usuario1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 366, 240, 40));

        BotonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 90, 40, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/AgregarAmigo.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarMouseClicked
        String usuario1 = Usuario1Field.getText();
        String usuario2 = Usuario2Field.getText();

        if (usuario1.isBlank() || usuario1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completa el campo de Usuario 1.", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (usuario2.isBlank() || usuario2.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completa el campo de Usuario 2.", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Main_UberSocial.uberSocial.agregarAmigo(usuario1, usuario2);

        if (Main_UberSocial.uberSocial.isMenuPrincipal()) {
            MenuPrincipal menuPrincipal = new MenuPrincipal();
            menuPrincipal.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_BotonAgregarMouseClicked

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        MenuPrincipal menuPrincipal = new MenuPrincipal();
        menuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarAmigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonAgregar;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField Usuario1Field;
    private javax.swing.JTextField Usuario2Field;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
