/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lab5_UberSocial;

import javax.swing.JOptionPane;

/**
 *
 * @author jenniferbueso
 */
public class AgregarCuenta extends javax.swing.JFrame {

    /**
     * Creates new form AgregarCuenta
     */
    public AgregarCuenta() {
        initComponents();
        
        FacebookIcon.setVisible(false);
        TwitterIcon.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonRegresar = new javax.swing.JLabel();
        BotonAgregar = new javax.swing.JLabel();
        TipoCuenta = new javax.swing.JComboBox<>();
        UsuarioField = new javax.swing.JTextField();
        FacebookIcon = new javax.swing.JLabel();
        TwitterIcon = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 90, 40, 30));

        BotonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 190, 40));

        TipoCuenta.setBackground(new java.awt.Color(255, 255, 255));
        TipoCuenta.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        TipoCuenta.setForeground(new java.awt.Color(0, 0, 0));
        TipoCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Facebook", "Twitter" }));
        TipoCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(TipoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 359, 220, 40));

        UsuarioField.setBackground(new java.awt.Color(202, 240, 248));
        UsuarioField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        UsuarioField.setForeground(new java.awt.Color(0, 0, 0));
        UsuarioField.setBorder(null);
        jPanel1.add(UsuarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 359, 240, 40));

        FacebookIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/FacebookIcon.png"))); // NOI18N
        jPanel1.add(FacebookIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 190, 160, 150));

        TwitterIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/TwitterIcon.png"))); // NOI18N
        jPanel1.add(TwitterIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 190, -1, 150));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/AgregarCuenta.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        MenuPrincipal menuPrincipal = new MenuPrincipal();
        menuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresarMouseClicked

    private void BotonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarMouseClicked
        String tipoCuenta = TipoCuenta.getSelectedItem().toString().toUpperCase();
        String usuario = UsuarioField.getText();
        
        if (tipoCuenta.equals(" ")) {
            JOptionPane.showMessageDialog(null, "Elije un Tipo de Cuenta.", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (usuario.isBlank() || usuario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completa el campo de Usuario.", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Main_UberSocial.uberSocial.agregarCuenta(usuario, tipoCuenta);
        
        if (Main_UberSocial.uberSocial.isMenuPrincipal()) {
            MenuPrincipal menuPrincipal = new MenuPrincipal();
            menuPrincipal.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_BotonAgregarMouseClicked

    private void TipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoCuentaActionPerformed
        String tipoCuenta = TipoCuenta.getSelectedItem().toString().toUpperCase();
        
        if (tipoCuenta.equals(" ")) {
            FacebookIcon.setVisible(false);
            TwitterIcon.setVisible(false);  
        } else if (tipoCuenta.equals("FACEBOOK")) {
            FacebookIcon.setVisible(true);
            TwitterIcon.setVisible(false);  
            FacebookIcon.setLocation(397, 190);
        } else if (tipoCuenta.equals("TWITTER")) {
            FacebookIcon.setVisible(false);
            TwitterIcon.setVisible(true);  
            TwitterIcon.setLocation(402, 190);
        }
    }//GEN-LAST:event_TipoCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonAgregar;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JLabel FacebookIcon;
    private javax.swing.JLabel Fondo;
    private javax.swing.JComboBox<String> TipoCuenta;
    private javax.swing.JLabel TwitterIcon;
    private javax.swing.JTextField UsuarioField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
