/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lab5_UberSocial;

import javax.swing.JOptionPane;

/**
 *
 * @author jenniferbueso
 */
public class AgregarComment extends javax.swing.JFrame {

    /**
     * Creates new form AgregarComment
     */
    public AgregarComment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AutorField = new javax.swing.JTextField();
        PostIdField = new javax.swing.JTextField();
        UsuarioField = new javax.swing.JTextField();
        BotonPublicar = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ComentarioField = new javax.swing.JTextArea();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AutorField.setBackground(new java.awt.Color(202, 240, 248));
        AutorField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        AutorField.setForeground(new java.awt.Color(0, 0, 0));
        AutorField.setBorder(null);
        jPanel1.add(AutorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 389, 250, 30));

        PostIdField.setBackground(new java.awt.Color(202, 240, 248));
        PostIdField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        PostIdField.setForeground(new java.awt.Color(0, 0, 0));
        PostIdField.setBorder(null);
        PostIdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PostIdFieldKeyTyped(evt);
            }
        });
        jPanel1.add(PostIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 305, 250, 30));

        UsuarioField.setBackground(new java.awt.Color(202, 240, 248));
        UsuarioField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        UsuarioField.setForeground(new java.awt.Color(0, 0, 0));
        UsuarioField.setBorder(null);
        jPanel1.add(UsuarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 222, 250, 30));

        BotonPublicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPublicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPublicarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonPublicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 150, 40));

        BotonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 90, 40, 30));

        jScrollPane1.setBorder(null);

        ComentarioField.setBackground(new java.awt.Color(202, 240, 248));
        ComentarioField.setColumns(20);
        ComentarioField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        ComentarioField.setForeground(new java.awt.Color(0, 0, 0));
        ComentarioField.setLineWrap(true);
        ComentarioField.setRows(5);
        ComentarioField.setBorder(null);
        jScrollPane1.setViewportView(ComentarioField);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 229, 270, 180));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/AgregarComment.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPublicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPublicarMouseClicked
        String usuario = UsuarioField.getText();
        int postID = -1;
        postID = Integer.parseInt(PostIdField.getText());
        String autor = AutorField.getText();
        String comentario = ComentarioField.getText();

        if (usuario.isBlank() || usuario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completa el campo de Usuario.", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (autor.isBlank() || autor.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completa el campo de Autor.", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (postID <= 0) {
            JOptionPane.showMessageDialog(null, "Post ID no válido.", "ID Inválido", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (comentario.isBlank() || comentario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completa el campo de Comentario.", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Main_UberSocial.uberSocial.agregarComment(usuario, postID, autor, comentario);

        if (Main_UberSocial.uberSocial.isMenuPrincipal()) {
            MenuPrincipal menuPrincipal = new MenuPrincipal();
            menuPrincipal.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_BotonPublicarMouseClicked

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        MenuPrincipal menuPrincipal = new MenuPrincipal();
        menuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresarMouseClicked

    private void PostIdFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PostIdFieldKeyTyped
        int tecla = evt.getKeyChar();
        boolean valido = tecla >= 48 && tecla <= 57;

        if(!valido){
            evt.consume();
        }
    }//GEN-LAST:event_PostIdFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarComment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarComment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarComment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarComment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarComment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AutorField;
    private javax.swing.JLabel BotonPublicar;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JTextArea ComentarioField;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField PostIdField;
    private javax.swing.JTextField UsuarioField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
