/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lab5_UberSocial;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jenniferbueso
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonAgregarComentario = new javax.swing.JLabel();
        BotonProfile = new javax.swing.JLabel();
        BotonAgregarAmigo = new javax.swing.JLabel();
        BotonAgregarPost = new javax.swing.JLabel();
        BotonAgregarCuenta = new javax.swing.JLabel();
        BotonNetbeans = new javax.swing.JLabel();
        BotonPensum = new javax.swing.JLabel();
        BotonJavaTickets = new javax.swing.JLabel();
        TextoFile = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAgregarComentario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregarComentario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarComentarioMouseClicked(evt);
            }
        });
        jPanel1.add(BotonAgregarComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 545, 70, 70));

        BotonProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonProfileMouseClicked(evt);
            }
        });
        jPanel1.add(BotonProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 544, 70, 70));

        BotonAgregarAmigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregarAmigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarAmigoMouseClicked(evt);
            }
        });
        jPanel1.add(BotonAgregarAmigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 543, 70, 70));

        BotonAgregarPost.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregarPost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarPostMouseClicked(evt);
            }
        });
        jPanel1.add(BotonAgregarPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 544, 70, 70));

        BotonAgregarCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarCuentaMouseClicked(evt);
            }
        });
        jPanel1.add(BotonAgregarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 542, 70, 70));

        BotonNetbeans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonNetbeans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonNetbeansMouseClicked(evt);
            }
        });
        jPanel1.add(BotonNetbeans, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 80, 80));

        BotonPensum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPensum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPensumMouseClicked(evt);
            }
        });
        jPanel1.add(BotonPensum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 110, 80));

        BotonJavaTickets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonJavaTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonJavaTicketsMouseClicked(evt);
            }
        });
        jPanel1.add(BotonJavaTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, 90));

        TextoFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextoFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextoFileMouseClicked(evt);
            }
        });
        jPanel1.add(TextoFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 130, 90));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/MenuPrincipal.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarCuentaMouseClicked
        AgregarCuenta agregarCuenta = new AgregarCuenta();
        agregarCuenta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonAgregarCuentaMouseClicked

    private void BotonAgregarPostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarPostMouseClicked
        AgregarPost agregarPost = new AgregarPost();
        agregarPost.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonAgregarPostMouseClicked

    private void BotonAgregarAmigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarAmigoMouseClicked
        AgregarAmigo agregarAmigo = new AgregarAmigo();
        agregarAmigo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonAgregarAmigoMouseClicked

    private void BotonProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonProfileMouseClicked
        Profile profile = new Profile();
        profile.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonProfileMouseClicked

    private void BotonAgregarComentarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarComentarioMouseClicked
        AgregarComment agregarComment = new AgregarComment();
        agregarComment.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonAgregarComentarioMouseClicked

    private void BotonPensumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPensumMouseClicked
        ImageIcon pensum = new ImageIcon("/Users/jenniferbueso/NetBeansProjects/Comment/src/Elementos/TurismoPensum.png");
        JOptionPane.showMessageDialog(null, "", "", JOptionPane.INFORMATION_MESSAGE, pensum);
    }//GEN-LAST:event_BotonPensumMouseClicked

    private void TextoFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoFileMouseClicked
        JOptionPane.showMessageDialog(null, "El ingeniero más relajo de toda UNITEC <3.", "Erick El Mejor", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_TextoFileMouseClicked

    private void BotonNetbeansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonNetbeansMouseClicked
        ImageIcon pensum = new ImageIcon("/Users/jenniferbueso/NetBeansProjects/Comment/src/Elementos/Netbeans.png");
        JOptionPane.showMessageDialog(null, "", "", JOptionPane.INFORMATION_MESSAGE, pensum);
    }//GEN-LAST:event_BotonNetbeansMouseClicked

    private void BotonJavaTicketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonJavaTicketsMouseClicked
        JOptionPane.showMessageDialog(null, "Archivo no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_BotonJavaTicketsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonAgregarAmigo;
    private javax.swing.JLabel BotonAgregarComentario;
    private javax.swing.JLabel BotonAgregarCuenta;
    private javax.swing.JLabel BotonAgregarPost;
    private javax.swing.JLabel BotonJavaTickets;
    private javax.swing.JLabel BotonNetbeans;
    private javax.swing.JLabel BotonPensum;
    private javax.swing.JLabel BotonProfile;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel TextoFile;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
